avatar: https://avatars.githubusercontent.com/u/91327160?v=4
background:
    path: https://i.ibb.co/PvcsS1qP/129045237-p0.jpg
    width: 2912
    height: 1632
favicon:
  href: /favicon.ico
  type: image/x-icon

function:
  globalToc: true
  wordCount: false
  copyCode: true

imageCDN:
  enable: false
  origin: /../../images/
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/

customStyles:
  - custom.css

iconlib:

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archives/
        - icon-container
    关于我:
        - /about/
        - icon-info-circle

widgets:
    - name: search
      enable: true
      options:
        search:
            type: engine
            url: https://cn.bing.com/search?q=site:example.com
    - name: social
      enable: true
      options:
        social:
            GitHub:
                - https://github.com/huanxherta
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .1)
            哔哩哔哩:
                - https://space.bilibili.com/503842971
                - icon-bilibili
                - rgb(231, 106, 141)
                - rgba(231, 106, 141, .1)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options:
        maxTagcloud: 17
    - name: hitokoto
      enable: true
      options:
        widgetHitokoto:
            loading_placeholder: '🚀 获取中...'
            loading_error_placeholder: '🐞 获取失败...'
    - name: archive
      enable: true
      options:
        widgetAchive:
            archive_type: 'year'
            show_count: true
    - name: recent_posts
      enable: true
    - name: link
      enable: false

copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url"

slotHead: |
  <script src="https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js"></script>

slotFooter: |

slotSidebar: |

slotComment: |

slotCopyright: |
  <strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可

slotArticleEnd: |
